### ISSUE TITLE
error about "grid.arrange"

### ISSUE THREAD

**Issue by tsungwu** [jonathankitt/tidytuesday_plots#1]
I got error message below, no package is found.
Error in grid.arrange(header, plot1, plot2, ncol = 2, nrow = 2, layout_matrix = rbind(c(1,  : 
  could not find function "grid.arrange"

**Comment by biorandomics** [comment]
Thanks for the comment, and my apologies for being so slow ... I'm new to git :-)
I got muddled up in the packages, "grid.arrange" is from "gridExtra", not "cowplot".
